/* global getFeed */
function getFeed(){
var feed = {
   "response":{
      "blog":{
         "title":"Winter Adventures",
         "name":"winter-adventures",
         "posts":7,
         "url":"http:\/\/winter-adventures.tumblr.com\/",
         "updated":1420737939,
         "description":"",
         "is_nsfw":false,
         "ask":false,
         "ask_page_title":"Ask me anything",
         "ask_anon":false,
         "share_likes":false
      },
      "posts":[
         {
            "blog_name":"winter-adventures",
            "id":104154340631,
            "post_url":"http:\/\/winter-adventures.tumblr.com\/post\/104154340631\/the-best-christmas-markets-in-the-uk-kelly-smith",
            "slug":"the-best-christmas-markets-in-the-uk-kelly-smith",
            "type":"photo",
            "date":"2014-12-02 12:23:00 GMT",
            "timestamp":1417522980,
            "state":"published",
            "format":"html",
            "reblog_key":"fpmnnc9m",
            "tags":[
               "Travel",
               "christmas",
               "britain",
               "winter",
               "london"
            ],
            "short_url":"http:\/\/tmblr.co\/ZHilwl1X05HqN",
            "highlighted":[

            ],
            "note_count":106,
            "caption":"<p><strong><span>The Best Christmas Markets In The UK<\/span><\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p>No need to head to the freezing cities of Europe this festive season, we\u2019ve got plenty of cheer and gift ideas right here in the UK to keep you feeling festive right through the holidays<\/p>\n<p><!-- more -->Christmas does seem to get earlier and earlier every year but if you\u2019re well and truly ready for a spot of festive cheer, there are plenty of places around the country that will help you enjoy the Christmas spirit.<\/p>\n\n<p>Here are some of our favourites.<\/p>\n\n<p><strong>Bath<\/strong><\/p>\n\n<p>Stallholders set up right between the Roman Baths and the Cathedral giving the Bath Christmas Market a beautiful backdrop and historic atmosphere.<\/p>\n\n<p>There\u2019s cheer and beer and local businesses selling artisan products from unique jewellery to handcrafted lamps and organic candles, all with a distinct West Country flavour. You can also buy cheese, beer and enjoy a mulled wine from local vendors. \u00a0<\/p>\n\n<p>Plus it\u2019s completely integrated into the city itself so you can pair a spot of Christmas marketeering with a water round the historic streets and boutique shops, stopping off at an authentic ale pub or two.<\/p>\n\n<p>When: November 27\u2013December 14<\/p>\n<p>More info: <a href=\"http:\/\/bathchristmasmarket.co.uk\/\">http:\/\/bathchristmasmarket.co.uk\/<\/a><\/p>\n\n<p><strong>Edinburgh<\/strong><\/p>\n\n<p>The Scottish capital is always a treat and during the festive season it\u2019s even better than usual with a European market selling gl\u00fchwein and German-inspired delicacies, as well as traditional Scotch markets with plenty of tartan and local produce.<\/p>\n\n<p>There\u2019s also an ice rink at Princes Street Gardens and a children\u2019s market with Santa Land, face painting and crafts<\/p>\n\n<p>When: November 21\u2013January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.edinburghschristmas.com\/\">http:\/\/www.edinburghschristmas.com\/<\/a><\/p>\n\n<p><strong>Birmingham<\/strong><\/p>\n\n<p>Still not always thought of as a destination in it\u2019s own right, Birmingham has so much to offer at Christmas.<\/p>\n\n<p>Its huge Frankfurt market claims to be the biggest German-themed outside Germany itself, selling delicious Christmas-themed footstuffs, leather goods and wooden toys among other crafts.<\/p>\n\n<p>But if you\u2019re not in the market for a schnitzel, Brum\u2019s Christmas markets have plenty more to offer. The Craft Market that runs alongside the Frankfurt market has locally-made produce such as hand-crafted soaps and toiletries, ceramics and glasswear, as well as local foods.<\/p>\n\n<p>When: November 13-December 22<\/p>\n<p>More Info: \u00a0http:\/\/visitbirmingham.com\/<\/p>\n\n<p><\/p>\n\n<p><strong>London<\/strong><\/p>\n<p><img alt=\"image\" src=\"https:\/\/31.media.tumblr.com\/20fabc027925b6fc0d8cbdf2c2e2e952\/tumblr_inline_nghdjs8a771sq0979.gif\"\/><\/p>\n\n<p>There\u2019s something undeniably special about London at Christmas. As well as the famous Christmas street lights and Harrods, Selfridges and all the department stores brightly a-glow, there are a variety of unmissable markets.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Barbican Christmas market (December 12 \u2013 22) will be showcasing 35 independent designers and artisans selling vintage and designer clothes, arts and crafts, jewellery, books and toys.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Winter Wonderland in Hyde Park (November 21 - January 4) isn\u2019t so much for Christmas shopping but is certainly worth stopping by to get into the Christmas spirit. Ice skating, Santa\u2019s Grotto, glittering lights and a giant wheel are all mixed in with festive food and drinking so if you\u2019re ready to start feeling festive go an enjoy it with the rest of Christmas-loving London.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Southbank Centre Christmas Market (November 11 - January 4) has everything festive you could want all with a stunning Thames backdrop. \u00a0As well as crafts, gifts and tasty treats, you can hop on the nearby London Eye to close out the evening with and extra special bang.<\/p>\n<p>When November 11 - January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.visitlondon.com\/tag\/christmas-markets\">http:\/\/www.visitlondon.com\/tag\/christmas-markets<\/a><\/p>\n\n<p><strong>York<\/strong><\/p>\n\n<p>York\u2019s annual St Nicholas Christmas Festival covers everything from Christmas present shopping to festive street entertainment, all nestled in amongst the iconic white stone buildings and impressive Minster.<\/p>\n<p>There are various events happening, including the Made In Yorkshire Fayre at the 15th-century Guildhall, the Medieval Market (November 27-30) at Barley Hall and chocolate-making workshops at York Cocoa House.<\/p>\n\n<p><\/p>\n\n<p>When: November 27\u2013December 21<\/p>\n<p>More Info: <a href=\"http:\/\/www.visityork.org\/\">http:\/\/www.visityork.org\/<\/a><\/p>\n\n<p><\/p>\n<p><strong>Best of the rest:\u00a0<\/strong><\/p>\n\n<p>If none of these are close by don\u2019t despair! With so much going on this December, you\u2019ll certainly be able to find a Christmas market closer to home with festivities happening in Stratford-Upon-Avon, St Albans, Winchester, Guildford, Portsmouth, Oxford, Exeter, Leeds, Bristol and Lincoln.\u00a0<\/p>\n\n<p>Many other towns and cities will have markets and fayres on for just one weekend or evena single day in the lead up to Christmas, so keep an eye out for local posters and support your local festivities.<\/p>\n\n<p><\/p>",
            "caption_abstract":"\n<p><strong><span>The Best Christmas Markets In The UK<\/span><\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p>No need to head to the freezing cities of Europe this festive season, we\u2019ve got plenty of cheer and gift ideas right here in the UK to keep you feeling festive right through the holidays<\/p>\n<p><\/p>\n",
            "reblog":{
               "tree_html":"",
               "comment":"<p><strong><span>The Best Christmas Markets In The UK<\/span><\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p>No need to head to the freezing cities of Europe this festive season, we&rsquo;ve got plenty of cheer and gift ideas right here in the UK to keep you feeling festive right through the holidays<\/p>\n<p>[[MORE]]Christmas does seem to get earlier and earlier every year but if you&rsquo;re well and truly ready for a spot of festive cheer, there are plenty of places around the country that will help you enjoy the Christmas spirit.<\/p>\n\n<p>Here are some of our favourites.<\/p>\n\n<p><strong>Bath<\/strong><\/p>\n\n<p>Stallholders set up right between the Roman Baths and the Cathedral giving the Bath Christmas Market a beautiful backdrop and historic atmosphere.<\/p>\n\n<p>There&rsquo;s cheer and beer and local businesses selling artisan products from unique jewellery to handcrafted lamps and organic candles, all with a distinct West Country flavour. You can also buy cheese, beer and enjoy a mulled wine from local vendors. &nbsp;<\/p>\n\n<p>Plus it&rsquo;s completely integrated into the city itself so you can pair a spot of Christmas marketeering with a water round the historic streets and boutique shops, stopping off at an authentic ale pub or two.<\/p>\n\n<p>When: November 27&ndash;December 14<\/p>\n<p>More info: <a href=\"http:\/\/bathchristmasmarket.co.uk\/\">http:\/\/bathchristmasmarket.co.uk\/<\/a><\/p>\n\n<p><strong>Edinburgh<\/strong><\/p>\n\n<p>The Scottish capital is always a treat and during the festive season it&rsquo;s even better than usual with a European market selling gl&uuml;hwein and German-inspired delicacies, as well as traditional Scotch markets with plenty of tartan and local produce.<\/p>\n\n<p>There&rsquo;s also an ice rink at Princes Street Gardens and a children&rsquo;s market with Santa Land, face painting and crafts<\/p>\n\n<p>When: November 21&ndash;January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.edinburghschristmas.com\/\">http:\/\/www.edinburghschristmas.com\/<\/a><\/p>\n\n<p><strong>Birmingham<\/strong><\/p>\n\n<p>Still not always thought of as a destination in it&rsquo;s own right, Birmingham has so much to offer at Christmas.<\/p>\n\n<p>Its huge Frankfurt market claims to be the biggest German-themed outside Germany itself, selling delicious Christmas-themed footstuffs, leather goods and wooden toys among other crafts.<\/p>\n\n<p>But if you&rsquo;re not in the market for a schnitzel, Brum&rsquo;s Christmas markets have plenty more to offer. The Craft Market that runs alongside the Frankfurt market has locally-made produce such as hand-crafted soaps and toiletries, ceramics and glasswear, as well as local foods.<\/p>\n\n<p>When: November 13-December 22<\/p>\n<p>More Info: &nbsp;http:\/\/visitbirmingham.com\/<\/p>\n\n<p><\/p>\n\n<p><strong>London<\/strong><\/p>\n<p><img alt=\"image\" src=\"https:\/\/31.media.tumblr.com\/20fabc027925b6fc0d8cbdf2c2e2e952\/tumblr_inline_nghdjs8a771sq0979.gif\"><\/p>\n\n<p>There&rsquo;s something undeniably special about London at Christmas. As well as the famous Christmas street lights and Harrods, Selfridges and all the department stores brightly a-glow, there are a variety of unmissable markets.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Barbican Christmas market (December 12 &ndash; 22) will be showcasing 35 independent designers and artisans selling vintage and designer clothes, arts and crafts, jewellery, books and toys.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Winter Wonderland in Hyde Park (November 21 - January 4) isn&rsquo;t so much for Christmas shopping but is certainly worth stopping by to get into the Christmas spirit. Ice skating, Santa&rsquo;s Grotto, glittering lights and a giant wheel are all mixed in with festive food and drinking so if you&rsquo;re ready to start feeling festive go an enjoy it with the rest of Christmas-loving London.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Southbank Centre Christmas Market (November 11 - January 4) has everything festive you could want all with a stunning Thames backdrop. &nbsp;As well as crafts, gifts and tasty treats, you can hop on the nearby London Eye to close out the evening with and extra special bang.<\/p>\n<p>When November 11 - January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.visitlondon.com\/tag\/christmas-markets\">http:\/\/www.visitlondon.com\/tag\/christmas-markets<\/a><\/p>\n\n<p><strong>York<\/strong><\/p>\n\n<p>York&rsquo;s annual St Nicholas Christmas Festival covers everything from Christmas present shopping to festive street entertainment, all nestled in amongst the iconic white stone buildings and impressive Minster.<\/p>\n<p>There are various events happening, including the Made In Yorkshire Fayre at the 15th-century Guildhall, the Medieval Market (November 27-30) at Barley Hall and chocolate-making workshops at York Cocoa House.<\/p>\n\n<p><\/p>\n\n<p>When: November 27&ndash;December 21<\/p>\n<p>More Info: <a href=\"http:\/\/www.visityork.org\/\">http:\/\/www.visityork.org\/<\/a><\/p>\n\n<p><\/p>\n<p><strong>Best of the rest:&nbsp;<\/strong><\/p>\n\n<p>If none of these are close by don&rsquo;t despair! With so much going on this December, you&rsquo;ll certainly be able to find a Christmas market closer to home with festivities happening in Stratford-Upon-Avon, St Albans, Winchester, Guildford, Portsmouth, Oxford, Exeter, Leeds, Bristol and Lincoln.&nbsp;<\/p>\n\n<p>Many other towns and cities will have markets and fayres on for just one weekend or evena single day in the lead up to Christmas, so keep an eye out for local posters and support your local festivities.<\/p>\n\n<p><\/p>"
            },
            "trail":[
               {
                  "blog":{
                     "name":"winter-adventures",
                     "theme":{
                        "header_full_width":500,
                        "header_full_height":280,
                        "header_focus_width":497,
                        "header_focus_height":280,
                        "avatar_shape":"square",
                        "background_color":"#FAFAFA",
                        "body_font":"Helvetica Neue",
                        "header_bounds":"0,498,280,1",
                        "header_image":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4.jpg",
                        "header_image_focused":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/PhInghavt\/tumblr_static_tumblr_static_76nslrflun40c4kkw0csgscc4_focused_v3.jpg",
                        "header_image_scaled":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4_2048_v2.jpg",
                        "header_stretch":true,
                        "link_color":"#529ECC",
                        "show_avatar":false,
                        "show_description":true,
                        "show_header_image":true,
                        "show_title":true,
                        "title_color":"#444444",
                        "title_font":"Helvetica Neue",
                        "title_font_weight":"regular"
                     }
                  },
                  "post":{
                     "id":"104154340631"
                  },
                  "content":"<p><strong><span>The Best Christmas Markets In The UK<\/span><\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p>No need to head to the freezing cities of Europe this festive season, we\u2019ve got plenty of cheer and gift ideas right here in the UK to keep you feeling festive right through the holidays<\/p>\n<p>[[MORE]]Christmas does seem to get earlier and earlier every year but if you\u2019re well and truly ready for a spot of festive cheer, there are plenty of places around the country that will help you enjoy the Christmas spirit.<\/p>\n\n<p>Here are some of our favourites.<\/p>\n\n<p><strong>Bath<\/strong><\/p>\n\n<p>Stallholders set up right between the Roman Baths and the Cathedral giving the Bath Christmas Market a beautiful backdrop and historic atmosphere.<\/p>\n\n<p>There\u2019s cheer and beer and local businesses selling artisan products from unique jewellery to handcrafted lamps and organic candles, all with a distinct West Country flavour. You can also buy cheese, beer and enjoy a mulled wine from local vendors. \u00a0<\/p>\n\n<p>Plus it\u2019s completely integrated into the city itself so you can pair a spot of Christmas marketeering with a water round the historic streets and boutique shops, stopping off at an authentic ale pub or two.<\/p>\n\n<p>When: November 27\u2013December 14<\/p>\n<p>More info: <a href=\"http:\/\/bathchristmasmarket.co.uk\/\">http:\/\/bathchristmasmarket.co.uk\/<\/a><\/p>\n\n<p><strong>Edinburgh<\/strong><\/p>\n\n<p>The Scottish capital is always a treat and during the festive season it\u2019s even better than usual with a European market selling gl\u00fchwein and German-inspired delicacies, as well as traditional Scotch markets with plenty of tartan and local produce.<\/p>\n\n<p>There\u2019s also an ice rink at Princes Street Gardens and a children\u2019s market with Santa Land, face painting and crafts<\/p>\n\n<p>When: November 21\u2013January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.edinburghschristmas.com\/\">http:\/\/www.edinburghschristmas.com\/<\/a><\/p>\n\n<p><strong>Birmingham<\/strong><\/p>\n\n<p>Still not always thought of as a destination in it\u2019s own right, Birmingham has so much to offer at Christmas.<\/p>\n\n<p>Its huge Frankfurt market claims to be the biggest German-themed outside Germany itself, selling delicious Christmas-themed footstuffs, leather goods and wooden toys among other crafts.<\/p>\n\n<p>But if you\u2019re not in the market for a schnitzel, Brum\u2019s Christmas markets have plenty more to offer. The Craft Market that runs alongside the Frankfurt market has locally-made produce such as hand-crafted soaps and toiletries, ceramics and glasswear, as well as local foods.<\/p>\n\n<p>When: November 13-December 22<\/p>\n<p>More Info: \u00a0http:\/\/visitbirmingham.com\/<\/p>\n\n<p><\/p>\n\n<p><strong>London<\/strong><\/p>\n<p><img alt=\"image\" src=\"https:\/\/31.media.tumblr.com\/20fabc027925b6fc0d8cbdf2c2e2e952\/tumblr_inline_nghdjs8a771sq0979.gif\"><\/p>\n\n<p>There\u2019s something undeniably special about London at Christmas. As well as the famous Christmas street lights and Harrods, Selfridges and all the department stores brightly a-glow, there are a variety of unmissable markets.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Barbican Christmas market (December 12 \u2013 22) will be showcasing 35 independent designers and artisans selling vintage and designer clothes, arts and crafts, jewellery, books and toys.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Winter Wonderland in Hyde Park (November 21 - January 4) isn\u2019t so much for Christmas shopping but is certainly worth stopping by to get into the Christmas spirit. Ice skating, Santa\u2019s Grotto, glittering lights and a giant wheel are all mixed in with festive food and drinking so if you\u2019re ready to start feeling festive go an enjoy it with the rest of Christmas-loving London.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>The Southbank Centre Christmas Market (November 11 - January 4) has everything festive you could want all with a stunning Thames backdrop. \u00a0As well as crafts, gifts and tasty treats, you can hop on the nearby London Eye to close out the evening with and extra special bang.<\/p>\n<p>When November 11 - January 4<\/p>\n<p>More Info: <a href=\"http:\/\/www.visitlondon.com\/tag\/christmas-markets\">http:\/\/www.visitlondon.com\/tag\/christmas-markets<\/a><\/p>\n\n<p><strong>York<\/strong><\/p>\n\n<p>York\u2019s annual St Nicholas Christmas Festival covers everything from Christmas present shopping to festive street entertainment, all nestled in amongst the iconic white stone buildings and impressive Minster.<\/p>\n<p>There are various events happening, including the Made In Yorkshire Fayre at the 15th-century Guildhall, the Medieval Market (November 27-30) at Barley Hall and chocolate-making workshops at York Cocoa House.<\/p>\n\n<p><\/p>\n\n<p>When: November 27\u2013December 21<\/p>\n<p>More Info: <a href=\"http:\/\/www.visityork.org\/\">http:\/\/www.visityork.org\/<\/a><\/p>\n\n<p><\/p>\n<p><strong>Best of the rest:\u00a0<\/strong><\/p>\n\n<p>If none of these are close by don\u2019t despair! With so much going on this December, you\u2019ll certainly be able to find a Christmas market closer to home with festivities happening in Stratford-Upon-Avon, St Albans, Winchester, Guildford, Portsmouth, Oxford, Exeter, Leeds, Bristol and Lincoln.\u00a0<\/p>\n\n<p>Many other towns and cities will have markets and fayres on for just one weekend or evena single day in the lead up to Christmas, so keep an eye out for local posters and support your local festivities.<\/p>\n\n<p><\/p>",
                  "is_root_item":true,
                  "is_current_item":true
               }
            ],
            "image_permalink":"http:\/\/winter-adventures.tumblr.com\/image\/104154340631",
            "photos":[
               {
                  "caption":"",
                  "alt_sizes":[
                     {
                        "width":500,
                        "height":281,
                        "url":"https:\/\/33.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_500.gif"
                     },
                     {
                        "width":400,
                        "height":225,
                        "url":"https:\/\/33.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_400.gif"
                     },
                     {
                        "width":250,
                        "height":141,
                        "url":"https:\/\/38.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_250.gif"
                     },
                     {
                        "width":100,
                        "height":56,
                        "url":"https:\/\/38.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_100.gif"
                     },
                     {
                        "width":75,
                        "height":75,
                        "url":"https:\/\/38.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_75sq.gif"
                     }
                  ],
                  "original_size":{
                     "width":500,
                     "height":281,
                     "url":"https:\/\/33.media.tumblr.com\/3b187e427db23fecb7292eee8b430dbe\/tumblr_nfyfr6eUGP1u4d88oo1_r4_500.gif"
                  }
               }
            ]
         },
         {
            "blog_name":"winter-adventures",
            "id":104154259661,
            "post_url":"http:\/\/winter-adventures.tumblr.com\/post\/104154259661\/tips-for-long-road-trips-with-children-kelly",
            "slug":"tips-for-long-road-trips-with-children-kelly",
            "type":"photo",
            "date":"2014-12-02 12:21:00 GMT",
            "timestamp":1417522860,
            "state":"published",
            "format":"html",
            "reblog_key":"9diKUQrL",
            "tags":[
               "Travel",
               "family",
               "kids",
               "holiday",
               "vacation"
            ],
            "short_url":"http:\/\/tmblr.co\/ZHilwl1X04_3D",
            "highlighted":[

            ],
            "note_count":4,
            "caption":"<p><strong>Tips For Long Road Trips With Children<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Taking the kids on a long road trip might fill you with dread but banish the \u2018are we nearly there yets\u2019 with our best advice for mobile family-time<\/span><\/p>\n<p><!-- more -->Confining children to anywhere for long periods of time can be a recipe for disaster but sometimes there\u2019s just no getting away from cooping them up in the car for a few hours for the greater good.<\/p>\n\n<p>But even the longest journeys to visit the farthest away relatives can be made far more pleasant for everyone with a few easy family travel lifesavers.<\/p>\n\n<p><strong>The Entertainment<\/strong><\/p>\n\n<p>In an ideal world we dish out a handheld computer game console, a book or a DVD and they\u2019re so engrossed we can sit in the front and read, listen to the radio or even indulge in some grown up chat.<\/p>\n\n<p>Sadly, though a DS, inbuilt DVD player or even a good old fashion novel will keep them going for a while, after a hour or few, even those with the best concentration will find it wandering.<\/p>\n\n<p>Of course you\u2019ve got old-school travelling games such as Eye Spy and Simon Says but they really do get old quick.<\/p>\n\n<p>So branch out and turn entertainer to make the hours race by.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Tell stories about your destination. Do a little research before you head off (or turn your 3G on and rely on your phone) and find a few real-life tales from where you\u2019re going.<\/p>\n\n<p>It\u2019s the ideal way to help the children connect with where they\u2019re headed and will make them more engaged in the journey if they know more about what they can do when you arrive. You can also tell true (or false) stories about relatives you\u2019re visiting. Which should amuse you if not them.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Get the whole car involved in some one-sentence storytelling. Go round and say a sentence each until you create a story. It\u2019s a surprisingly fun way to pass the time and incentivise their imagination by saying you\u2019ll send the best story off to a publisher.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Add a competitive element. Whether it\u2019s \u2018who can tell me the best fact about where we\u2019re going\u2019 or car colour bingo (where the first person to count 10 cars of their chosen colour wins), make the prize the choice of what to play next on the mp3 player or the choice of bedroom when you arrive and you\u2019ll be amazed how much effort they\u2019ll put in.<\/p>\n\n<p>And mix it up. If they\u2019ve been quiet for an hour playing with a tablet or reading and you can feel them getting fidgety, mix it up with something completely different \u2013 such as a singalong to divide the journey into specific activity chunks.<\/p>\n\n<p><\/p>\n<p><strong>The Props<\/strong><\/p>\n\n<p>As with most things parenting-related, being organised is essential. You can kill a good few hours simply by having the right props to work with.<\/p>\n\n<p>Depending on what you have available to you, you will need some configuration of the following items:<\/p>\n\n<p>A tablet with pre-loaded apps, an in car DVD player, audiobooks and singalong tapes, pens and paper for keeping score or writing down your stories. And whatever you do, do not forget an in-car for any electronic device you bring.<\/p>\n\n<p>Audio books are available from Audible or iTunes or buy a CD version for the car stereo for when your storytelling abilities wane.<\/p>\n\n<p><strong>The Picnic<\/strong><\/p>\n\n<p>On long journey\u2019s it\u2019s inevitable that you\u2019ll have to stop for refreshments. Buying for the whole family at a service station can really add up, so make a picnic the night before and work 45 minutes or an hour into your schedule so everyone can have a real break and let off steam (including the poor driver).<\/p>\n\n<p>If you can find a picnic spot that will allow the kids to run around, so much the better, though these are more common on the Continent than in the UK.<\/p>\n\n<p>When it comes to food, go for a healthy balanced range for the picnic and avoid fizzy drinks and sweets as these will give everyone a sugar and E-number rush that will make the proceeding few hours a nightmare all round.<\/p>\n\n<p>Dishes such as brown bread sandwiches and wholewheat pasta salads have a low GI giving slow-release energy rather than a sugar high and crash. If you know they\u2019ll want something sweet for afters stick to fruits for pudding \u2013 but eat them whole rather than mashing them into a sugary smoothie or juice.<\/p>\n\n<p>It might be tempting to stock up on sweets and chocolates for the car journey but as well as worsening car sickness, they\u2019ll give them too quick a hit of energy. Instead, cucumber and carrot crudit\u00e9s with hummus are good for snacks or if forcing vegetables down is to hard, popcorn is ideal.<\/p>\n\n<p>For drinks stick to water or watered down fruit juice.<\/p>\n\n<p><\/p>\n<p><strong>Enjoy The Journey<\/strong><\/p>\n\n<p>It can sounds cheesy and a bit impossible at times, but if you can make the journey as much fun as you can for everyone then it will seem shorter and future trips won\u2019t take on an air of an ordeal.<\/p>\n\n<p>Good luck!<\/p>\n\n<p><\/p>",
            "caption_abstract":"\n<p><strong>Tips For Long Road Trips With Children<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Taking the kids on a long road trip might fill you with dread but banish the \u2018are we nearly there yets\u2019 with our best advice for mobile family-time<\/span><\/p>\n<p><\/p>\n",
            "reblog":{
               "tree_html":"",
               "comment":"<p><strong>Tips For Long Road Trips With Children<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Taking the kids on a long road trip might fill you with dread but banish the &lsquo;are we nearly there yets&rsquo; with our best advice for mobile family-time<\/span><\/p>\n<p>[[MORE]]Confining children to anywhere for long periods of time can be a recipe for disaster but sometimes there&rsquo;s just no getting away from cooping them up in the car for a few hours for the greater good.<\/p>\n\n<p>But even the longest journeys to visit the farthest away relatives can be made far more pleasant for everyone with a few easy family travel lifesavers.<\/p>\n\n<p><strong>The Entertainment<\/strong><\/p>\n\n<p>In an ideal world we dish out a handheld computer game console, a book or a DVD and they&rsquo;re so engrossed we can sit in the front and read, listen to the radio or even indulge in some grown up chat.<\/p>\n\n<p>Sadly, though a DS, inbuilt DVD player or even a good old fashion novel will keep them going for a while, after a hour or few, even those with the best concentration will find it wandering.<\/p>\n\n<p>Of course you&rsquo;ve got old-school travelling games such as Eye Spy and Simon Says but they really do get old quick.<\/p>\n\n<p>So branch out and turn entertainer to make the hours race by.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Tell stories about your destination. Do a little research before you head off (or turn your 3G on and rely on your phone) and find a few real-life tales from where you&rsquo;re going.<\/p>\n\n<p>It&rsquo;s the ideal way to help the children connect with where they&rsquo;re headed and will make them more engaged in the journey if they know more about what they can do when you arrive. You can also tell true (or false) stories about relatives you&rsquo;re visiting. Which should amuse you if not them.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Get the whole car involved in some one-sentence storytelling. Go round and say a sentence each until you create a story. It&rsquo;s a surprisingly fun way to pass the time and incentivise their imagination by saying you&rsquo;ll send the best story off to a publisher.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Add a competitive element. Whether it&rsquo;s &lsquo;who can tell me the best fact about where we&rsquo;re going&rsquo; or car colour bingo (where the first person to count 10 cars of their chosen colour wins), make the prize the choice of what to play next on the mp3 player or the choice of bedroom when you arrive and you&rsquo;ll be amazed how much effort they&rsquo;ll put in.<\/p>\n\n<p>And mix it up. If they&rsquo;ve been quiet for an hour playing with a tablet or reading and you can feel them getting fidgety, mix it up with something completely different &ndash; such as a singalong to divide the journey into specific activity chunks.<\/p>\n\n<p><\/p>\n<p><strong>The Props<\/strong><\/p>\n\n<p>As with most things parenting-related, being organised is essential. You can kill a good few hours simply by having the right props to work with.<\/p>\n\n<p>Depending on what you have available to you, you will need some configuration of the following items:<\/p>\n\n<p>A tablet with pre-loaded apps, an in car DVD player, audiobooks and singalong tapes, pens and paper for keeping score or writing down your stories. And whatever you do, do not forget an in-car for any electronic device you bring.<\/p>\n\n<p>Audio books are available from Audible or iTunes or buy a CD version for the car stereo for when your storytelling abilities wane.<\/p>\n\n<p><strong>The Picnic<\/strong><\/p>\n\n<p>On long journey&rsquo;s it&rsquo;s inevitable that you&rsquo;ll have to stop for refreshments. Buying for the whole family at a service station can really add up, so make a picnic the night before and work 45 minutes or an hour into your schedule so everyone can have a real break and let off steam (including the poor driver).<\/p>\n\n<p>If you can find a picnic spot that will allow the kids to run around, so much the better, though these are more common on the Continent than in the UK.<\/p>\n\n<p>When it comes to food, go for a healthy balanced range for the picnic and avoid fizzy drinks and sweets as these will give everyone a sugar and E-number rush that will make the proceeding few hours a nightmare all round.<\/p>\n\n<p>Dishes such as brown bread sandwiches and wholewheat pasta salads have a low GI giving slow-release energy rather than a sugar high and crash. If you know they&rsquo;ll want something sweet for afters stick to fruits for pudding &ndash; but eat them whole rather than mashing them into a sugary smoothie or juice.<\/p>\n\n<p>It might be tempting to stock up on sweets and chocolates for the car journey but as well as worsening car sickness, they&rsquo;ll give them too quick a hit of energy. Instead, cucumber and carrot crudit&eacute;s with hummus are good for snacks or if forcing vegetables down is to hard, popcorn is ideal.<\/p>\n\n<p>For drinks stick to water or watered down fruit juice.<\/p>\n\n<p><\/p>\n<p><strong>Enjoy The Journey<\/strong><\/p>\n\n<p>It can sounds cheesy and a bit impossible at times, but if you can make the journey as much fun as you can for everyone then it will seem shorter and future trips won&rsquo;t take on an air of an ordeal.<\/p>\n\n<p>Good luck!<\/p>\n\n<p><\/p>"
            },
            "trail":[
               {
                  "blog":{
                     "name":"winter-adventures",
                     "theme":{
                        "header_full_width":500,
                        "header_full_height":280,
                        "header_focus_width":497,
                        "header_focus_height":280,
                        "avatar_shape":"square",
                        "background_color":"#FAFAFA",
                        "body_font":"Helvetica Neue",
                        "header_bounds":"0,498,280,1",
                        "header_image":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4.jpg",
                        "header_image_focused":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/PhInghavt\/tumblr_static_tumblr_static_76nslrflun40c4kkw0csgscc4_focused_v3.jpg",
                        "header_image_scaled":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4_2048_v2.jpg",
                        "header_stretch":true,
                        "link_color":"#529ECC",
                        "show_avatar":false,
                        "show_description":true,
                        "show_header_image":true,
                        "show_title":true,
                        "title_color":"#444444",
                        "title_font":"Helvetica Neue",
                        "title_font_weight":"regular"
                     }
                  },
                  "post":{
                     "id":"104154259661"
                  },
                  "content":"<p><strong>Tips For Long Road Trips With Children<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Taking the kids on a long road trip might fill you with dread but banish the \u2018are we nearly there yets\u2019 with our best advice for mobile family-time<\/span><\/p>\n<p>[[MORE]]Confining children to anywhere for long periods of time can be a recipe for disaster but sometimes there\u2019s just no getting away from cooping them up in the car for a few hours for the greater good.<\/p>\n\n<p>But even the longest journeys to visit the farthest away relatives can be made far more pleasant for everyone with a few easy family travel lifesavers.<\/p>\n\n<p><strong>The Entertainment<\/strong><\/p>\n\n<p>In an ideal world we dish out a handheld computer game console, a book or a DVD and they\u2019re so engrossed we can sit in the front and read, listen to the radio or even indulge in some grown up chat.<\/p>\n\n<p>Sadly, though a DS, inbuilt DVD player or even a good old fashion novel will keep them going for a while, after a hour or few, even those with the best concentration will find it wandering.<\/p>\n\n<p>Of course you\u2019ve got old-school travelling games such as Eye Spy and Simon Says but they really do get old quick.<\/p>\n\n<p>So branch out and turn entertainer to make the hours race by.<\/p>\n<p>-<span class=\"Apple-tab-span\"> <\/span>Tell stories about your destination. Do a little research before you head off (or turn your 3G on and rely on your phone) and find a few real-life tales from where you\u2019re going.<\/p>\n\n<p>It\u2019s the ideal way to help the children connect with where they\u2019re headed and will make them more engaged in the journey if they know more about what they can do when you arrive. You can also tell true (or false) stories about relatives you\u2019re visiting. Which should amuse you if not them.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Get the whole car involved in some one-sentence storytelling. Go round and say a sentence each until you create a story. It\u2019s a surprisingly fun way to pass the time and incentivise their imagination by saying you\u2019ll send the best story off to a publisher.<\/p>\n\n<p>-<span class=\"Apple-tab-span\"> <\/span>Add a competitive element. Whether it\u2019s \u2018who can tell me the best fact about where we\u2019re going\u2019 or car colour bingo (where the first person to count 10 cars of their chosen colour wins), make the prize the choice of what to play next on the mp3 player or the choice of bedroom when you arrive and you\u2019ll be amazed how much effort they\u2019ll put in.<\/p>\n\n<p>And mix it up. If they\u2019ve been quiet for an hour playing with a tablet or reading and you can feel them getting fidgety, mix it up with something completely different \u2013 such as a singalong to divide the journey into specific activity chunks.<\/p>\n\n<p><\/p>\n<p><strong>The Props<\/strong><\/p>\n\n<p>As with most things parenting-related, being organised is essential. You can kill a good few hours simply by having the right props to work with.<\/p>\n\n<p>Depending on what you have available to you, you will need some configuration of the following items:<\/p>\n\n<p>A tablet with pre-loaded apps, an in car DVD player, audiobooks and singalong tapes, pens and paper for keeping score or writing down your stories. And whatever you do, do not forget an in-car for any electronic device you bring.<\/p>\n\n<p>Audio books are available from Audible or iTunes or buy a CD version for the car stereo for when your storytelling abilities wane.<\/p>\n\n<p><strong>The Picnic<\/strong><\/p>\n\n<p>On long journey\u2019s it\u2019s inevitable that you\u2019ll have to stop for refreshments. Buying for the whole family at a service station can really add up, so make a picnic the night before and work 45 minutes or an hour into your schedule so everyone can have a real break and let off steam (including the poor driver).<\/p>\n\n<p>If you can find a picnic spot that will allow the kids to run around, so much the better, though these are more common on the Continent than in the UK.<\/p>\n\n<p>When it comes to food, go for a healthy balanced range for the picnic and avoid fizzy drinks and sweets as these will give everyone a sugar and E-number rush that will make the proceeding few hours a nightmare all round.<\/p>\n\n<p>Dishes such as brown bread sandwiches and wholewheat pasta salads have a low GI giving slow-release energy rather than a sugar high and crash. If you know they\u2019ll want something sweet for afters stick to fruits for pudding \u2013 but eat them whole rather than mashing them into a sugary smoothie or juice.<\/p>\n\n<p>It might be tempting to stock up on sweets and chocolates for the car journey but as well as worsening car sickness, they\u2019ll give them too quick a hit of energy. Instead, cucumber and carrot crudit\u00e9s with hummus are good for snacks or if forcing vegetables down is to hard, popcorn is ideal.<\/p>\n\n<p>For drinks stick to water or watered down fruit juice.<\/p>\n\n<p><\/p>\n<p><strong>Enjoy The Journey<\/strong><\/p>\n\n<p>It can sounds cheesy and a bit impossible at times, but if you can make the journey as much fun as you can for everyone then it will seem shorter and future trips won\u2019t take on an air of an ordeal.<\/p>\n\n<p>Good luck!<\/p>\n\n<p><\/p>",
                  "is_root_item":true,
                  "is_current_item":true
               }
            ],
            "image_permalink":"http:\/\/winter-adventures.tumblr.com\/image\/104154259661",
            "photos":[
               {
                  "caption":"",
                  "alt_sizes":[
                     {
                        "width":700,
                        "height":467,
                        "url":"https:\/\/41.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_1280.jpg"
                     },
                     {
                        "width":500,
                        "height":334,
                        "url":"https:\/\/41.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_500.jpg"
                     },
                     {
                        "width":400,
                        "height":267,
                        "url":"https:\/\/40.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_400.jpg"
                     },
                     {
                        "width":250,
                        "height":167,
                        "url":"https:\/\/40.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_250.jpg"
                     },
                     {
                        "width":100,
                        "height":67,
                        "url":"https:\/\/41.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_100.jpg"
                     },
                     {
                        "width":75,
                        "height":75,
                        "url":"https:\/\/41.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_75sq.jpg"
                     }
                  ],
                  "original_size":{
                     "width":700,
                     "height":467,
                     "url":"https:\/\/41.media.tumblr.com\/857d7175bf04587387e30f8e494c0f5a\/tumblr_nfyfn8Z0KA1u4d88oo1_r2_1280.jpg"
                  }
               }
            ]
         },
         {
            "blog_name":"winter-adventures",
            "id":104154174031,
            "post_url":"http:\/\/winter-adventures.tumblr.com\/post\/104154174031\/how-to-keep-the-kids-entertained-this-winter",
            "slug":"how-to-keep-the-kids-entertained-this-winter",
            "type":"photo",
            "date":"2014-12-02 12:18:00 GMT",
            "timestamp":1417522680,
            "state":"published",
            "format":"html",
            "reblog_key":"vGco1uo3",
            "tags":[
               "kids",
               "christmas",
               "sports",
               "winter",
               "advice"
            ],
            "short_url":"http:\/\/tmblr.co\/ZHilwl1X04f9F",
            "highlighted":[

            ],
            "note_count":2,
            "caption":"<p><strong>How To Keep The Kids Entertained This Winter<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Five awesome things to do indoors when the weather\u2019s rubbish and it\u2019s all dark outside<\/span><\/p>\n<p><!-- more -->As hard to believe as it is, winter and the onset of indoor-play season has begun and now it\u2019s cold and dark outside you can\u2019t just pack the children off into the back garden to have their fun.<\/p>\n\n<p>So instead you need to be more creative to stop them driving you bananas. But fear not! We have some great ideas to keep the kids busy all winter long.<\/p>\n\n<p><strong>Natural Art<\/strong><\/p>\n\n<p>At the weekend, embrace the few hours of daylight we do have and take your brood along to your local park on a craft-material-finding expedition.<\/p>\n\n<p>Give them each a plastic bag and tell them to collect anything they\u2019d like to paint or decorate, or use in a collage when they get back home. It might be winter but nature still has plenty to offer.\u00a0<\/p>\n\n<p>Conkers, twigs, snail shells and fallen leaves are all ideal and when you get home you can make collages or use dried leaves for leaf-printing by covering them in paint and pressing them onto paper.<\/p>\n\n<p>Make sure you collect in all the bags and look through them at the end of the day though \u2013 you don\u2019t want to find a mouldy, worm-filled collection a few weeks later! Dry out any natural materials in the airing cupboard to use for future indoor creative play over the next few months.<\/p>\n\n<p><\/p>\n<p><strong>Indoor Balloon Sports\u00a0<\/strong><\/p>\n\n<p>This is how Judy Murray claims to have created two tennis aces. Trying to keep Andy and Jamie entertained in the usually grim Scottish weather led to plenty of weekends spent innovating games to play indoors.<\/p>\n\n<p>Some of the Murrays\u2019 favourites included balloon volleyball and of course, tennis. Just set up the \u2018court\u2019 and then lay out some rules before you let them lose with a balloon. If they\u2019re starting to get a bit good, throw in a few more balloons to keep things interesting.<\/p>\n\n<p>When yours win Wimbledon you can thank us\u2026<\/p>\n\n<p><strong>Treasure Hunt<\/strong><\/p>\n\n<p>Treasure hunting doesn\u2019t have to be for the annual Easter Egg Hunt. You can make this into great developmental fun because while they might claim to hate school, children love learning if it\u2019s done in an innovative and creative way.<\/p>\n\n<p>And though this does take a little work on your part it\u2019ll keep them busy for hours.<\/p>\n\n<p>Write clues, create Crystal-Maze style working-together tasks and hide the rewards around the house for them to find. If you\u2019re a crafty type you can have fun with the clues, or there are websites that you can print of a basic framework that you can customise for their children and your house.<\/p>\n\n<p>Try Nature Detectives (<a href=\"http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm\">http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm<\/a>), Quick Hunts (<a href=\"http:\/\/www.quickhunts.com\/\">http:\/\/www.quickhunts.com\/<\/a>) or \u00a0Kids at Lovetoknow.com (<a href=\"http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues\">http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues<\/a>) for printable \u00a0scavenger inspiration.<\/p>\n\n<p><strong>Recreate Britain\u2019s Got Talent In Your Living Room<\/strong><\/p>\n\n<p>Give them the dressing up box, nominate some songs and then get ready with your phone\u2019s video camera.<\/p>\n\n<p>Cut out numbers from cardboard boxes for authentic-looking scores, but be tactical \u2013 the last thing you\u2019re after iss tears from the loser\u2026<\/p>\n\n<p><strong>Make Christmas Decorations<\/strong><\/p>\n\n<p>Get creative in the kitchen by making dough that you can bake hard and varnish to create Christmas tree ornaments.<\/p>\n\n<p>A basic recipe is:<\/p>\n\n<p>1 mug of plain flour<\/p>\n<p>1 mug of salt<\/p>\n<p>(up to) 1 mug of water (or as much as you need)<\/p>\n\n<p>Mix all the dry ingredients together and then add water a little at a time until you start to form a dough-like consistency. Too sticky? Add \u00a0more flour. Too crumbly? Add more water. When it\u2019s ready you\u2019ll be able to squeeze and mould it like a dough but it won\u2019t come off on your fingers.\u00a0<\/p>\n\n<p>Then leave your budding Anish Kapoors to work out their creative juices. When they\u2019ve made their masterpieces stick the narrow end of a teaspoon through the top to make a hole that you can tie string through to hang them on the tree.<\/p>\n\n<p>Then once the dough\u2019s been baked you can paint the works of art with acrylic paints and preserve them with varnish to enjoy for many Christmasses to come.<\/p>\n\n<p>Winter playtime can be trickier than summer but when you get it right, it\u2019s even more rewarding and fun to share with your children.\u00a0<\/p>",
            "caption_abstract":"\n<p><strong>How To Keep The Kids Entertained This Winter<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Five awesome things to do indoors when the weather\u2019s rubbish and it\u2019s all dark outside<\/span><\/p>\n<p><\/p>\n",
            "reblog":{
               "tree_html":"",
               "comment":"<p><strong>How To Keep The Kids Entertained This Winter<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Five awesome things to do indoors when the weather&rsquo;s rubbish and it&rsquo;s all dark outside<\/span><\/p>\n<p>[[MORE]]As hard to believe as it is, winter and the onset of indoor-play season has begun and now it&rsquo;s cold and dark outside you can&rsquo;t just pack the children off into the back garden to have their fun.<\/p>\n\n<p>So instead you need to be more creative to stop them driving you bananas. But fear not! We have some great ideas to keep the kids busy all winter long.<\/p>\n\n<p><strong>Natural Art<\/strong><\/p>\n\n<p>At the weekend, embrace the few hours of daylight we do have and take your brood along to your local park on a craft-material-finding expedition.<\/p>\n\n<p>Give them each a plastic bag and tell them to collect anything they&rsquo;d like to paint or decorate, or use in a collage when they get back home. It might be winter but nature still has plenty to offer.&nbsp;<\/p>\n\n<p>Conkers, twigs, snail shells and fallen leaves are all ideal and when you get home you can make collages or use dried leaves for leaf-printing by covering them in paint and pressing them onto paper.<\/p>\n\n<p>Make sure you collect in all the bags and look through them at the end of the day though &ndash; you don&rsquo;t want to find a mouldy, worm-filled collection a few weeks later! Dry out any natural materials in the airing cupboard to use for future indoor creative play over the next few months.<\/p>\n\n<p><\/p>\n<p><strong>Indoor Balloon Sports&nbsp;<\/strong><\/p>\n\n<p>This is how Judy Murray claims to have created two tennis aces. Trying to keep Andy and Jamie entertained in the usually grim Scottish weather led to plenty of weekends spent innovating games to play indoors.<\/p>\n\n<p>Some of the Murrays&rsquo; favourites included balloon volleyball and of course, tennis. Just set up the &lsquo;court&rsquo; and then lay out some rules before you let them lose with a balloon. If they&rsquo;re starting to get a bit good, throw in a few more balloons to keep things interesting.<\/p>\n\n<p>When yours win Wimbledon you can thank us&hellip;<\/p>\n\n<p><strong>Treasure Hunt<\/strong><\/p>\n\n<p>Treasure hunting doesn&rsquo;t have to be for the annual Easter Egg Hunt. You can make this into great developmental fun because while they might claim to hate school, children love learning if it&rsquo;s done in an innovative and creative way.<\/p>\n\n<p>And though this does take a little work on your part it&rsquo;ll keep them busy for hours.<\/p>\n\n<p>Write clues, create Crystal-Maze style working-together tasks and hide the rewards around the house for them to find. If you&rsquo;re a crafty type you can have fun with the clues, or there are websites that you can print of a basic framework that you can customise for their children and your house.<\/p>\n\n<p>Try Nature Detectives (<a href=\"http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm\">http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm<\/a>), Quick Hunts (<a href=\"http:\/\/www.quickhunts.com\/\">http:\/\/www.quickhunts.com\/<\/a>) or &nbsp;Kids at Lovetoknow.com (<a href=\"http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues\">http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues<\/a>) for printable &nbsp;scavenger inspiration.<\/p>\n\n<p><strong>Recreate Britain&rsquo;s Got Talent In Your Living Room<\/strong><\/p>\n\n<p>Give them the dressing up box, nominate some songs and then get ready with your phone&rsquo;s video camera.<\/p>\n\n<p>Cut out numbers from cardboard boxes for authentic-looking scores, but be tactical &ndash; the last thing you&rsquo;re after iss tears from the loser&hellip;<\/p>\n\n<p><strong>Make Christmas Decorations<\/strong><\/p>\n\n<p>Get creative in the kitchen by making dough that you can bake hard and varnish to create Christmas tree ornaments.<\/p>\n\n<p>A basic recipe is:<\/p>\n\n<p>1 mug of plain flour<\/p>\n<p>1 mug of salt<\/p>\n<p>(up to) 1 mug of water (or as much as you need)<\/p>\n\n<p>Mix all the dry ingredients together and then add water a little at a time until you start to form a dough-like consistency. Too sticky? Add &nbsp;more flour. Too crumbly? Add more water. When it&rsquo;s ready you&rsquo;ll be able to squeeze and mould it like a dough but it won&rsquo;t come off on your fingers.&nbsp;<\/p>\n\n<p>Then leave your budding Anish Kapoors to work out their creative juices. When they&rsquo;ve made their masterpieces stick the narrow end of a teaspoon through the top to make a hole that you can tie string through to hang them on the tree.<\/p>\n\n<p>Then once the dough&rsquo;s been baked you can paint the works of art with acrylic paints and preserve them with varnish to enjoy for many Christmasses to come.<\/p>\n\n<p>Winter playtime can be trickier than summer but when you get it right, it&rsquo;s even more rewarding and fun to share with your children.&nbsp;<\/p>"
            },
            "trail":[
               {
                  "blog":{
                     "name":"winter-adventures",
                     "theme":{
                        "header_full_width":500,
                        "header_full_height":280,
                        "header_focus_width":497,
                        "header_focus_height":280,
                        "avatar_shape":"square",
                        "background_color":"#FAFAFA",
                        "body_font":"Helvetica Neue",
                        "header_bounds":"0,498,280,1",
                        "header_image":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4.jpg",
                        "header_image_focused":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/PhInghavt\/tumblr_static_tumblr_static_76nslrflun40c4kkw0csgscc4_focused_v3.jpg",
                        "header_image_scaled":"http:\/\/static.tumblr.com\/553d861a7a54a84435e22369897ab564\/vsykktf\/uHDnghavt\/tumblr_static_76nslrflun40c4kkw0csgscc4_2048_v2.jpg",
                        "header_stretch":true,
                        "link_color":"#529ECC",
                        "show_avatar":false,
                        "show_description":true,
                        "show_header_image":true,
                        "show_title":true,
                        "title_color":"#444444",
                        "title_font":"Helvetica Neue",
                        "title_font_weight":"regular"
                     }
                  },
                  "post":{
                     "id":"104154174031"
                  },
                  "content":"<p><strong>How To Keep The Kids Entertained This Winter<\/strong><\/p>\n<p>Kelly Smith<\/p>\n<p><span>Five awesome things to do indoors when the weather\u2019s rubbish and it\u2019s all dark outside<\/span><\/p>\n<p>[[MORE]]As hard to believe as it is, winter and the onset of indoor-play season has begun and now it\u2019s cold and dark outside you can\u2019t just pack the children off into the back garden to have their fun.<\/p>\n\n<p>So instead you need to be more creative to stop them driving you bananas. But fear not! We have some great ideas to keep the kids busy all winter long.<\/p>\n\n<p><strong>Natural Art<\/strong><\/p>\n\n<p>At the weekend, embrace the few hours of daylight we do have and take your brood along to your local park on a craft-material-finding expedition.<\/p>\n\n<p>Give them each a plastic bag and tell them to collect anything they\u2019d like to paint or decorate, or use in a collage when they get back home. It might be winter but nature still has plenty to offer.\u00a0<\/p>\n\n<p>Conkers, twigs, snail shells and fallen leaves are all ideal and when you get home you can make collages or use dried leaves for leaf-printing by covering them in paint and pressing them onto paper.<\/p>\n\n<p>Make sure you collect in all the bags and look through them at the end of the day though \u2013 you don\u2019t want to find a mouldy, worm-filled collection a few weeks later! Dry out any natural materials in the airing cupboard to use for future indoor creative play over the next few months.<\/p>\n\n<p><\/p>\n<p><strong>Indoor Balloon Sports\u00a0<\/strong><\/p>\n\n<p>This is how Judy Murray claims to have created two tennis aces. Trying to keep Andy and Jamie entertained in the usually grim Scottish weather led to plenty of weekends spent innovating games to play indoors.<\/p>\n\n<p>Some of the Murrays\u2019 favourites included balloon volleyball and of course, tennis. Just set up the \u2018court\u2019 and then lay out some rules before you let them lose with a balloon. If they\u2019re starting to get a bit good, throw in a few more balloons to keep things interesting.<\/p>\n\n<p>When yours win Wimbledon you can thank us\u2026<\/p>\n\n<p><strong>Treasure Hunt<\/strong><\/p>\n\n<p>Treasure hunting doesn\u2019t have to be for the annual Easter Egg Hunt. You can make this into great developmental fun because while they might claim to hate school, children love learning if it\u2019s done in an innovative and creative way.<\/p>\n\n<p>And though this does take a little work on your part it\u2019ll keep them busy for hours.<\/p>\n\n<p>Write clues, create Crystal-Maze style working-together tasks and hide the rewards around the house for them to find. If you\u2019re a crafty type you can have fun with the clues, or there are websites that you can print of a basic framework that you can customise for their children and your house.<\/p>\n\n<p>Try Nature Detectives (<a href=\"http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm\">http:\/\/www.naturedetectives.org.uk\/download\/treasure_hunt_springsummer.htm<\/a>), Quick Hunts (<a href=\"http:\/\/www.quickhunts.com\/\">http:\/\/www.quickhunts.com\/<\/a>) or \u00a0Kids at Lovetoknow.com (<a href=\"http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues\">http:\/\/kids.lovetoknow.com\/wiki\/Free_Treasure_Hunt_Clues<\/a>) for printable \u00a0scavenger inspiration.<\/p>\n\n<p><strong>Recreate Britain\u2019s Got Talent In Your Living Room<\/strong><\/p>\n\n<p>Give them the dressing up box, nominate some songs and then get ready with your phone\u2019s video camera.<\/p>\n\n<p>Cut out numbers from cardboard boxes for authentic-looking scores, but be tactical \u2013 the last thing you\u2019re after iss tears from the loser\u2026<\/p>\n\n<p><strong>Make Christmas Decorations<\/strong><\/p>\n\n<p>Get creative in the kitchen by making dough that you can bake hard and varnish to create Christmas tree ornaments.<\/p>\n\n<p>A basic recipe is:<\/p>\n\n<p>1 mug of plain flour<\/p>\n<p>1 mug of salt<\/p>\n<p>(up to) 1 mug of water (or as much as you need)<\/p>\n\n<p>Mix all the dry ingredients together and then add water a little at a time until you start to form a dough-like consistency. Too sticky? Add \u00a0more flour. Too crumbly? Add more water. When it\u2019s ready you\u2019ll be able to squeeze and mould it like a dough but it won\u2019t come off on your fingers.\u00a0<\/p>\n\n<p>Then leave your budding Anish Kapoors to work out their creative juices. When they\u2019ve made their masterpieces stick the narrow end of a teaspoon through the top to make a hole that you can tie string through to hang them on the tree.<\/p>\n\n<p>Then once the dough\u2019s been baked you can paint the works of art with acrylic paints and preserve them with varnish to enjoy for many Christmasses to come.<\/p>\n\n<p>Winter playtime can be trickier than summer but when you get it right, it\u2019s even more rewarding and fun to share with your children.\u00a0<\/p>",
                  "is_root_item":true,
                  "is_current_item":true
               }
            ],
            "image_permalink":"http:\/\/winter-adventures.tumblr.com\/image\/104154174031",
            "photos":[
               {
                  "caption":"",
                  "alt_sizes":[
                     {
                        "width":700,
                        "height":486,
                        "url":"https:\/\/40.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_1280.jpg"
                     },
                     {
                        "width":500,
                        "height":347,
                        "url":"https:\/\/40.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_500.jpg"
                     },
                     {
                        "width":400,
                        "height":278,
                        "url":"https:\/\/40.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_400.jpg"
                     },
                     {
                        "width":250,
                        "height":174,
                        "url":"https:\/\/41.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_250.jpg"
                     },
                     {
                        "width":100,
                        "height":69,
                        "url":"https:\/\/36.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_100.jpg"
                     },
                     {
                        "width":75,
                        "height":75,
                        "url":"https:\/\/40.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_75sq.jpg"
                     }
                  ],
                  "original_size":{
                     "width":700,
                     "height":486,
                     "url":"https:\/\/40.media.tumblr.com\/37db6d77ea4feeb43574d81e7af79fce\/tumblr_nfyfj57EwS1u4d88oo1_r2_1280.jpg"
                  }
               }
            ]
         }
      ],
      "total_posts":7
   }
};

return feed;

}
